service: login-api-abha
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1
plugins:
  - serverless-offline
  - serverless-plugin-common-excludes
functions:
  hello:
    handler: handler.hello
    events:
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true
